### ISSUE TITLE
Unity support

### ISSUE THREAD

**Issue by amit-nath30** [fexolm/GServer#30]
Unable to use this in Unity 2019, as system.reflection and system.reflection.emit not unavailable in unity. Any way to use this in unity

Thanks

**Comment by fexolm** [comment]
Hello @amit-nath30, this project was not been maintained for a long time, and I would recommend you to use https://github.com/RevenantX/LiteNetLib instead, as it is a lot better maintained.

**Comment by fexolm** [comment]
As for your question, I would recommend you to build GServer shared library and reference it in your unity project. This way you should avoid those errors.

**Comment by fexolm** [comment]
You may also want to remove all that CodeGen staff from GServer and serialize your structures by hand.
CodeGen is an experimental feature that does some CLR injections at runtime. As far as I remember, I got some security warnings in windows, when I was trying to use that. On Linux, it works well.

**Comment by amit-nath30** [comment]
thank you for your reply,
